#!/bin/bash


MERKLEDAG_SERVER=${MERKLEDAG_SERVER:-http://localhost:8080}


fail() {
    echo $@ >&2
    exit 1
}


usage() {
    echo "Usage: $(basename $0) <command> <action> [args...]"
    echo
    echo "Commands:"
    echo "    block [list|get|store|delete]"
    echo "    ref [list|get|set]"
    echo "    data [create|get|put]"
}


call_api() {
    local method=$1
    local path=$2
    shift 2
    echo "API: $method $path" >&2
    curl $CURL_OPTS -X $method ${MERKLEDAG_SERVER}${path} "$@"
}


if [[ $1 == "help" ]]; then
    HELP=1
    shift
fi


case $1 in
    block)
        case $2 in
            list)
                [[ $HELP == 1 ]] && echo "Usage: block list [query=val ...]"
                call_api GET /blocks/
                ;;

            get)
                [[ $HELP == 1 ]] && echo "Usage: block get <id>"
                [[ -n $3 ]] || fail "Usage: block get <id>"
                call_api GET /blocks/$3
                ;;

            store)
                [[ $HELP == 1 ]] && echo "Usage: block store [file]"
                call_api POST /blocks/ \
                    --header 'Content-Type: application/octet-stream' \
                    --data-binary @${3:--}
                ;;

            delete)
                [[ $HELP == 1 ]] && echo "Usage: block delete <id>"
                [[ -n $3 ]] || fail "Usage: block delete <id>"
                call_api DELETE /blocks/$3
                ;;

            *)
                usage
                fail "Bad block command"
                ;;
        esac
        ;;

    ref)
        case $2 in
            list)
                [[ $HELP == 1 ]] && echo "Usage: ref list [query=val ...]"
                call_api GET /refs/
                ;;

            get)
                [[ $HELP == 1 ]] && echo "Usage: ref get <name>"
                [[ -n $3 ]] || fail "Usage: ref get <name>"
                call_api GET /refs/$3
                ;;

            set)
                [[ $HELP == 1 ]] && echo "ref set <name> <id>"
                [[ -n $3 && -n $4 ]] || fail "Usage: ref set <name> <id>"
                call_api PUT /refs/$3 --data "value=$4"
                ;;

            *)
                usage
                fail "Bad ref command"
                ;;
        esac
        ;;

    data)
        case $2 in
            create)
                [[ $HELP == 1 ]] && echo "data create [file]"
                call_api POST /data/ \
                    --header 'Content-Type: application/edn' \
                    --data-binary @${3:--}
                ;;
            get)
                [[ $HELP == 1 ]] && echo "data get <id-or-name>[/path]*"
                call_api GET /data/$3
                ;;

            put)
                [[ $HELP == 1 ]] && echo "data put <name>[/path]* < input"
                fail "NYI"
                ;;

            *)
                usage
                fail "Bad data command"
                ;;
        esac
        ;;

    *)
        usage
        [[ $HELP == 1 ]] || fail "Bad command section"
        ;;
esac
